/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  about: [
    "about/README",
    {
      type: "category",
      label: "Tableland network",

      // Or, point to a specific page as the category's landing page
      link: {
        type: "doc",
        id: "sdk/README",
      },
      items: ["about/tableland/what-is-tableland"],
    },
    {
      type: "category",
      label: "Blockchain basics",
      link: {
        type: "generated-index",
      },
      items: ["about/blockchain/what-is-blockchain"],
    },
  ],
  build: [
    "build/README",
    {
      type: "category",
      label: "SDK",
      collapsed: false,
      link: {
        type: "doc",
        id: "sdk/README",
      },
      items: [
        "sdk/getting-started",
        "sdk/connect",
        "sdk/create",
        "sdk/write",
        "sdk/read",
      ],
    },
    {
      type: "category",
      label: "CLI",
      link: {
        type: "generated-index",
      },
      items: [
        "cli/getting-started",
        "cli/connect",
        "cli/create",
        "cli/write",
        "cli/read",
      ],
    },
    {
      type: "category",
      label: "Smart contracts",
      link: {
        type: "generated-index",
      },
      items: [
        "smart-contracts/getting-started",
        "smart-contracts/connect",
        "smart-contracts/create",
        "smart-contracts/write",
        "smart-contracts/read",
      ],
    },
  ],
  sql: [
    {
      type: "category",
      label: "SQL",
      link: {
        type: "generated-index",
      },
      items: ["sql/sql-spec"],
    },
  ],
  tutorials: [
    {
      type: "category",
      label: "Tutorials",
      link: {
        type: "generated-index",
      },
      items: ["tutorials/dynamic-nft-solidity", "tutorials/dynamic-nft-p5js"],
    },
  ],
  contributing: [
    {
      type: "category",
      label: "Contributing",
      link: {
        type: "generated-index",
      },
      items: [
        "contribute/guidelines",
        "contribute/style-guide",
        "contribute/maintainers",
      ],
    },
  ],
};

module.exports = sidebars;
