/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Tableland Docs",
  "tagline": "Explore how to store and query data on Tableland—the SQL database for blockchains.",
  "url": "http://localhost:3000",
  "baseUrl": "/",
  "onBrokenLinks": "log",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/tableland/favicon.ico",
  "organizationName": "tablelandnetwork",
  "projectName": "docs",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "markdown": {
    "mermaid": true
  },
  "themes": [
    [
      "@easyops-cn/docusaurus-search-local",
      {
        "hashed": true
      }
    ],
    "@docusaurus/theme-mermaid"
  ],
  "stylesheets": [
    {
      "href": "https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css",
      "type": "text/css",
      "integrity": "sha384-AfEj0r4/OFrOo5t7NnNe46zW/tFgW6x/bCJG8FqQCEo3+Aro6EYUG4+cU+KJWu/X",
      "crossorigin": "anonymous"
    }
  ],
  "plugins": [
    "@docusaurus/theme-live-codeblock",
    [
      "docusaurus-plugin-dotenv",
      {
        "path": "./.env"
      }
    ]
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./config/sidebars.js",
          "routeBasePath": "/",
          "editUrl": "https://github.com/tablelandnetwork/docs/tree/main/",
          "showLastUpdateTime": true,
          "breadcrumbs": true,
          "remarkPlugins": [
            null,
            null,
            {
              "sync": true
            }
          ],
          "rehypePlugins": [
            null
          ],
          "showLastUpdateAuthor": true
        },
        "blog": {
          "showReadingTime": true,
          "editUrl": "https://github.com/tablelandnetwork/docs/tree/main"
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        },
        "sitemap": {
          "changefreq": "weekly",
          "priority": 0.5,
          "ignorePatterns": [
            "/tags/**"
          ],
          "filename": "sitemap.xml"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/tableland/site-banner.png",
    "metadata": [
      {
        "name": "description",
        "content": "The official documentation for the Tableland Network. Build web3 with SQL using smart contracts, SDKs, and APIs, and learn all about the protocol."
      },
      {
        "name": "og:title",
        "content": "Tableland Docs: API Reference, Quickstart Guides, and Integrations"
      },
      {
        "name": "twitter:title",
        "content": "Tableland Docs"
      },
      {
        "name": "twitter:description",
        "content": "The official documentation for the Tableland Network. Build web3 with SQL."
      },
      {
        "name": "og:site_name",
        "content": "Tableland Docs"
      },
      {
        "name": "keywords",
        "content": "tableland, docs, documentation, web3, crypto, blockchain, SQL, SQLite, relational, database"
      }
    ],
    "mermaid": {
      "theme": {
        "light": "neutral",
        "dark": "dark"
      },
      "options": {
        "fontFamily": "Inter"
      }
    },
    "docs": {
      "sidebar": {
        "autoCollapseCategories": true,
        "hideable": true
      },
      "versionPersistence": "localStorage"
    },
    "navbar": {
      "hideOnScroll": false,
      "title": "",
      "logo": {
        "alt": "Tableland logo",
        "src": "/img/tableland/logo-black.svg",
        "srcDark": "/img/tableland/logo-white.svg",
        "width": 200,
        "target": "_self"
      },
      "items": [
        {
          "type": "docSidebar",
          "position": "left",
          "sidebarId": "concepts",
          "label": "Concepts"
        },
        {
          "type": "docSidebar",
          "position": "left",
          "sidebarId": "develop",
          "label": "Develop"
        },
        {
          "type": "doc",
          "docId": "/category/tutorials",
          "position": "left",
          "label": "Tutorials"
        },
        {
          "label": "Community",
          "position": "right",
          "items": [
            {
              "type": "docSidebar",
              "sidebarId": "contribute",
              "label": "Contribute"
            },
            {
              "type": "docSidebar",
              "sidebarId": "rigs",
              "label": "Rigs NFT"
            },
            {
              "href": "https://dev.tableland.xyz",
              "label": "Tech blog",
              "target": "_blank",
              "rel": null
            },
            {
              "href": "https://discord.com/invite/dc8EBEhGbg",
              "label": "Discord",
              "target": "_blank",
              "rel": null
            },
            {
              "href": "https://twitter.com/tableland__",
              "label": "Twitter",
              "target": "_blank",
              "rel": null
            },
            {
              "href": "https://tableland.xyz/pilot-program/",
              "label": "Pilot Program",
              "target": "_blank",
              "rel": null
            }
          ]
        },
        {
          "href": "https://github.com/tablelandnetwork/",
          "position": "right",
          "className": "header-github-link",
          "aria-label": "GitHub repository"
        },
        {
          "type": "search",
          "position": "right"
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 4
    },
    "customFooter": {
      "links": [
        {
          "title": "Developers",
          "items": [
            {
              "to": "/category/sdk",
              "label": "SDK"
            },
            {
              "to": "/category/cli",
              "label": "CLI"
            },
            {
              "to": "/category/api",
              "label": "API"
            },
            {
              "to": "/category/smart-contracts",
              "label": "Smart contracts"
            },
            {
              "to": "/concepts/sql/sql-spec",
              "label": "SQL spec"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "to": "contribute",
              "label": "Contribute"
            },
            {
              "to": "rigs",
              "label": "Rigs NFT"
            },
            {
              "href": "https://discord.com/invite/dc8EBEhGbg",
              "label": "Discord"
            },
            {
              "href": "https://twitter.com/tableland__",
              "label": "Twitter"
            },
            {
              "href": "https://www.youtube.com/@tablelandxyz",
              "label": "YouTube"
            },
            {
              "href": "https://tableland.xyz/pilot-program/",
              "label": "Pilot Program"
            },
            {
              "href": "https://dev.tableland.xyz/showcase/",
              "label": "Showcase"
            }
          ]
        },
        {
          "title": "Company",
          "items": [
            {
              "href": "https://dev.tableland.xyz",
              "label": "Tech Blog"
            },
            {
              "href": "https://mirror.xyz/tableland.eth",
              "label": "Main Blog"
            },
            {
              "href": "https://tableland.xyz",
              "label": "Main site"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/tablelandnetwork/"
            },
            {
              "href": "https://linktr.ee/textileio",
              "label": "Team"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2023 Tableland Network"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#82aaff",
          "backgroundColor": "#2D1339"
        },
        "styles": [
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(162, 191, 252)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgba(239, 83, 80, 0.56)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "inserted",
              "attr-name"
            ],
            "style": {
              "color": "#beffad",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgba(255, 255, 255, 0.5)"
            }
          },
          {
            "types": [
              "string",
              "url"
            ],
            "style": {
              "color": "#beffad"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(214, 222, 235)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "#ff5e5e"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "style": {
              "color": "#fff"
            }
          },
          {
            "types": [
              "selector",
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "class-name",
              "delimiter"
            ],
            "style": {
              "color": "#ffcb6b"
            }
          },
          {
            "types": [
              "tag",
              "operator",
              "keyword"
            ],
            "style": {
              "color": "#ca79ee"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "property"
            ],
            "style": {
              "color": "rgb(128, 203, 196)"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          }
        ]
      },
      "defaultLanguage": "javascript",
      "additionalLanguages": [
        "solidity"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        },
        {
          "className": "code-block-error-line",
          "line": "error"
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "announcementBar": {
      "id": "announcementBar-0",
      "content": "Give Tableland a ⭐️ on <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://github.com/tablelandnetwork\">GitHub</a> and follow us on <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://twitter.com/tableland__\" >Twitter</a>",
      "isCloseable": true
    },
    "liveCodeBlock": {
      "playgroundPosition": "bottom"
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "scripts": [],
  "headTags": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
